[2025-06-16T11:48:11.922+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T11:48:07.992921+00:00 [queued]>
[2025-06-16T11:48:11.927+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T11:48:07.992921+00:00 [queued]>
[2025-06-16T11:48:11.927+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-16T11:48:11.939+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-16 11:48:07.992921+00:00
[2025-06-16T11:48:11.948+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2025-06-16T11:48:11.952+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-06-16T11:48:07.992921+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp3i_kmnw1']
[2025-06-16T11:48:11.961+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask stream_data_from_api
[2025-06-16T11:48:12.120+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T11:48:07.992921+00:00 [running]> on host 02746d0f3966
[2025-06-16T11:48:12.945+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T11:48:07.992921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T11:48:07.992921+00:00'
[2025-06-16T11:48:13.394+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.6', 29092)]>: connecting to broker:29092 [('10.89.0.6', 29092) IPv4]
[2025-06-16T11:48:13.444+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('10.89.0.6', 29092)]>: Broker version identified as 2.6
[2025-06-16T11:48:13.448+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Connection complete.
[2025-06-16T11:48:14.708+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('10.89.0.6', 29092)]>: connecting to broker:29092 [('10.89.0.6', 29092) IPv4]
[2025-06-16T11:48:14.711+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Connection complete.
[2025-06-16T11:48:14.712+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Closing connection. 
[2025-06-16T11:48:14.779+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-06-16T11:49:07.414+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-16T11:49:07.424+0000] {logging_mixin.py:149} INFO - an error occurred: list index out of range
[2025-06-16T11:49:10.417+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-16T11:49:10.419+0000] {logging_mixin.py:149} INFO - an error occurred: list index out of range
[2025-06-16T11:49:12.863+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-16T11:49:12.866+0000] {logging_mixin.py:149} INFO - an error occurred: list index out of range
[2025-06-16T11:49:13.718+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Closing connection. 
[2025-06-16T11:49:13.721+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-16T11:49:13.800+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250616T114807, start_date=20250616T114811, end_date=20250616T114913
[2025-06-16T11:49:13.896+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-16T11:49:13.993+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
