[2025-06-16T10:35:10.328+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T10:35:04.070994+00:00 [queued]>
[2025-06-16T10:35:10.351+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T10:35:04.070994+00:00 [queued]>
[2025-06-16T10:35:10.352+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-16T10:35:10.396+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-16 10:35:04.070994+00:00
[2025-06-16T10:35:10.432+0000] {standard_task_runner.py:57} INFO - Started process 188 to run task
[2025-06-16T10:35:10.473+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-06-16T10:35:04.070994+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpni8o4aoy']
[2025-06-16T10:35:10.483+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask stream_data_from_api
[2025-06-16T10:35:10.749+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T10:35:04.070994+00:00 [running]> on host d05f2c8635f0
[2025-06-16T10:35:12.116+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T10:35:04.070994+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T10:35:04.070994+00:00'
[2025-06-16T10:35:13.128+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.133+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.133+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.134+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.134+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.135+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.136+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.136+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.138+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.139+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.04 secs
[2025-06-16T10:35:13.195+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.198+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.198+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.201+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.203+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.205+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.205+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.208+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.208+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.209+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.11 secs
[2025-06-16T10:35:13.332+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.336+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.337+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.341+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.343+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.345+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.346+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.347+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.348+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.349+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.22 secs
[2025-06-16T10:35:13.582+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.592+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.596+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.597+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.597+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.598+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.600+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:13.603+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:13.605+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:13.605+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.44 secs
[2025-06-16T10:35:14.091+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:14.112+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:14.113+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:14.119+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:14.123+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:14.123+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:14.125+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:14.127+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:14.128+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:14.129+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.83 secs
[2025-06-16T10:35:14.978+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:14.990+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:14.991+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:14.994+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:14.998+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:15.004+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:15.005+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: connecting to broker:29092 [('10.89.0.19', 29092) IPv4]
[2025-06-16T10:35:15.006+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-16T10:35:15.006+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.19', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-16T10:35:15.007+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.11 secs
[2025-06-16T10:35:15.122+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 44, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms = 5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-06-16T10:35:15.257+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250616T103504, start_date=20250616T103510, end_date=20250616T103515
[2025-06-16T10:35:15.294+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task stream_data_from_api (NoBrokersAvailable; 188)
[2025-06-16T10:35:15.365+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-06-16T10:35:15.483+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
